### ISSUE TITLE
[FEATURE] We need a minmax function. With predicate support ideally.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1294]
I wrote this:

```
return { eve::min(x,y), eve::max(x, y) };
```

But, unfortunately gcc does not optimise it properly.

https://godbolt.org/z/EaPG85KMx

**Comment by jtlap** [comment]
I played a bit with CE
if I write that:
    const auto test = eve::is_less(x,y);
    const auto mini = eve::if_else(test,x,y);
    const auto maxi = eve::if_else(test,y,x);
    return { mini, maxi };
instead of calling min and max
it seems that the codegen of g++ and clang are reversed and now clang looks bad gcc better...

**Comment by jtlap** [comment]
Another remark is that for floats min(a,b) and max(a,b) may not return the same result as the code I put in the preceding comment because of nans, (That's why the pedantic and numeric versions of thesz functions)

**Comment by jtlap** [comment]
More than that I wonder If pipelining does not make the 4 instructions codegen better than the 3 instructions one.
Is it a question for Joel or for you?

**Comment by jfalcou** [comment]
> Another remark is that for floats min(a,b) and max(a,b) may not return the same result as the code I put in the preceding comment because of nans, (That's why the pedantic and numeric versions of these functions)

NaN are to be respected for singular min max, it is too complicated to garantee anything.

**Comment by jtlap** [comment]
for minmax?

**Comment by DenisYaroshevskiy** [comment]
>
>Another remark is that for floats min(a,b) and max(a,b) may not return the same result as the code I put in the preceding > comment because of nans, (That's why the pedantic and numeric versions of these functions)

For a custom predicate for equivalents min is first and max is second.
[{a, 1}, {a, 0}] => compare by first min returns {a, 1}, max - {a, 0};

For `is_less` `is_greater` - we can treat them as total ordering and `minmax` becomes: return `{min(x, y), max(x, y)};`

**Comment by jfalcou** [comment]
On non X86 arch, min/max always exists so the trivial implementation stands.
On x86: 
- on AVX2, only 64 bits integral are bad becasue they lack so many intrinsic before AVX512. The code proposed by jtlap is OK for int64 and abd for uint64 because unsigned < on x86 can't be written properly.
- on AVX, we need a slice() to go back to SSE4 min/max
- SSE4 is fine except for 64bits ints
- SSE2 is meh but this is SSE2, jtlap's code mitigate the issue for signed types.

I propose minmax by default do the obvious code and we patch X86 for the types that are problematic.
Unless we find a way to do min/max without unsigned comparison, some cases will be bad anyhow.
