### ISSUE TITLE
[BUG] Links in README are broken

### ISSUE THREAD

**Issue by igagis** [jfalcou/eve#1707]
**Describe the bug**
Links in *Getting started* section of README.md are broken.

**To Reproduce**
Click the links.

**Expected behavior**
links lead to a website

**Comment by DenisYaroshevskiy** [comment]
Sorry about that - https://jfalcou.github.io/eve/intro-01.html

I'm going to leave the issue open for a couple of days - let me know if you have issues.

Also - if you can concisely phrase the problem you are trying to solve - I am happy to have a look at that as well.

**Comment by igagis** [comment]
I thought it is clear. Links in README.md are broken.

For example, the first link is https://jfalcou.github.io/eve/tutorials.html, clicking it gives 404.

**Comment by DenisYaroshevskiy** [comment]
> I thought it is clear.

Sorry for confusion. I communicated what I meant poorly

I meant: yes - they are broken. I tried to fix them, but that actually turned out not that obvious, asked @jfalcou  - hopefully he will.

===

Here is the link I'd suggest you start with: https://jfalcou.github.io/eve/intro-01.html
Let me know if you have any issues with the library - on this issue for example. I will do my best to help you.

**Comment by igagis** [comment]
I'm just browsing at the moment, no particular use of the lib in plans yet. I'll keep it in mind. Thanks!

**Comment by jfalcou** [comment]
Oh yeah, I updated the layout of the doc yesterday and forgot to change the README's, I am doing it this afternoon

**Comment by jfalcou** [comment]
Should be good now. Feel free to close this issue if it's OK for you or tell us what's still non working

**Comment by igagis** [comment]
works now
