### ISSUE TITLE
[FEATURE] nbtrue, proper implementation

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#478]
- [x] nbtrue(top_bits)
 - [x] use top bits implementation
 - [x] arm - proper implementation
 - [ ] If something can be done on power - do power.
 - [x]  UPD: also - can it be called `count_true`? c++ algorithm is called count.

**Comment by jfalcou** [comment]
nbtrue is the Matlab inspired name and it stucks because of old history.
count is a better name cause we can layter have count(v,w) that basically do count( v == w )

**Comment by DenisYaroshevskiy** [comment]
@jfalcou :
but we have first_true - it should be count true then.
Or it should be first, but that doesn't make sense.

**Comment by jfalcou** [comment]
`first_true` exists because : 
 - it's mapped to some intrinsics
 - is a very fundamental operation

It indeed sets a precedent for `***_true`, I concur.

In term of counting things, let's have a look at the standard:
 - `count` counts the # of things equal to a value in a sequence
 - `count_if` counts the # of thing validating a predicate in a sequence
 
So `count(s,v)` is in fact `count_if(s, [](auto e) { return e ==v });`
The standard has no "default value" or "default predicate" in fact.

So I think you're right. But, I think we can also trivially provide `count_if` and `count` next to `count_true` by virtue that :

 - `count(w, v)` <=> `count_true(w == v)`
 - `count_if(w, pred)` <=> `count_true( pred(w) )`
 
This may also means that we can provide a convenience :
 - `first_if(w, pred)` <=> `first_true( pred(w) )` ?
 
 What do you think?

**Comment by DenisYaroshevskiy** [comment]
I rly rly rly don't like it.

It's a reduction on logical it should stay a reduction logical.

You can call `count_true(pred(w))` nobody will stop you, what's so convenient abount count_if.

The reason for `true` is there should be `count_false` `first_false`, `last_true` , `nth_true`, `nth_false` etc.

And it should be one naming system. It can be `_set` `_cleared` instead but it's  a worth fit for logical. Maybe for `top_bits` it's good.

**Comment by jfalcou** [comment]
Good. I agree on count_true, we'll see the other later.
