### ISSUE TITLE
[BUG] rename is equal -> equal_to + follow naming conventions for the std

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#675]
std has some of the predicates that we cave but in scalar. I think we should name our versions the same way

**Comment by jtlap** [comment]
I do not agree with the change

1) all our element-wise predicates are homogeneously named is_xxx. and return a logical
2) our real predicates as all, any etc. do not share this property
3) std::equal_to is a function object supposed to return a bool (i.e. a real predicate) by : 

bool operator()( const T& lhs, const T& rhs ) const;

If we want to have an equal_to to follow standard, its semantic on wide could be 
   all(is_equal_to(a,b)) 
because equal_to is a global equality of two variables 

However std has also a equal algorithm
template< class InputIt1, class InputIt2 >

constexpr bool equal( InputIt1 first1, InputIt1 last1,
                      InputIt2 first2 );

this could be an alias for is_equal an also an algorithm for eve

**Comment by DenisYaroshevskiy** [comment]
@jtlap - this is a suggestion.

My argument is

1. I suggest that we rename all of the relevant ones: `equal_to`, `not_equal_to`, `greater`, `less`, `greater_equal`, `less_equal` - this will be following std conventions
2. I don't quite understand
3. Well fundamentally `operator==` should return a `bool`. Since we are already breaking that, breaking the predicates doesn't seem like much.

I see these functors as predicates for algorithms. In the stl we'd write smth like:

```
std::sort(f, l, std::greater);
```

However for eve we'll write:
```
eve::sort(wide, eve::is_greater);
```

**Comment by jtlap** [comment]
Ok, but I this case I suggest to have the std names as alias of our names, so eve::sort(wide, eve::is_greater);
and eve::sort(wide, eve::greater); will be equivalent.
example of doing so is is_pow2 and has_single_bit

**Comment by DenisYaroshevskiy** [comment]
@jtlap 
I prefer as is to 2 different functions doing the same thing.
I don't have a strong enough opinion tbh, I just saw that and figured it was weird.

@jfalcou - can you weigh in, what do you think?

**Comment by jfalcou** [comment]
The naming of wide predicate as `is_` was the result of a long discussion ages ago for  1/ be homogeneous 2/ not giving the false sens to users that it was indeed the equivalent of the std functor.

I would like if we keep the is_* naming in place. In the old code base we had functor that did all(is_equal) etc in one scoop and they were called compare_equal, compare_less etc.

What we can do is :
 1 - having eve::greater maps to the combo of all + the is_*, some can be optimized via top bits btw
 2 - having aliases like @jtlap proposed, thing we already have for other functions we had before std standardized them
 3 - stay as we are
 
 My preferences in order are 2, 3, 1

**Comment by DenisYaroshevskiy** [comment]
I'd won't touch it then - I don't think 2 versions are terribly helpful.
I just assumed this was an oversight, my bad.

**Comment by jfalcou** [comment]
No problems :)
