### ISSUE TITLE
[BUG] tests failures

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#812]
There are two reported

```
05:56:30 ~/falcoudev/build/clang-12$ unit/unit.algo.reduce.exe
[EVE] - Target: eve::avx2_ - Assertions: Disabled - PRNG Seed: 18102008
[SCENARIO] - Check reduce (with T = eve::wide<signed char, eve::fixed<1ULL>>)
[SCENARIO] - Check reduce (with T = eve::wide<unsigned char, eve::fixed<32>>)
[SCENARIO] - Check reduce (with T = eve::wide<short, eve::fixed<16>>)
[SCENARIO] - Check reduce (with T = eve::wide<unsigned short, eve::fixed<4>>)
[SCENARIO] - Check reduce (with T = eve::wide<int, eve::fixed<8>>)
[SCENARIO] - Check reduce (with T = eve::wide<float, eve::fixed<8>>)
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 91 == 89 occured instead.
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 89 == 85 occured instead.
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 86 == 78 occured instead.
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 82 == 70 occured instead.
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 77 == 59 occured instead.
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 71 == 47 occured instead.
reduce.cpp:46 - **FAILED** - Expecting: res == expected but 64 == 32 occured instead.
reduce.cpp:57 - **FAILED** - Expecting: res == expected but 64 == 32 occured instead.
```

Seems like float to char conversion problem. That's ub.

```
06:00:16 ~/falcoudev/build/clang-12$ unit/unit.memory.store.conditional.exe
[EVE] - Target: eve::avx2_ - Assertions: Disabled - PRNG Seed: 18102008
[SCENARIO] - Check store behavior with ignore (with T = eve::wide<float, eve::fixed<1ULL>>)
conditional.cpp:34 - **FAILED** - Expecting: data == what.back() but 17.000000 == 1.000000 occured instead.
conditional.cpp:37 - **FAILED** - Expecting: data == what.front() but 17.000000 == 1.000000 occured instead.
conditional.cpp:40 - **FAILED** - Expecting: data == what.front() but 17.000000 == 1.000000 occured instead.
conditional.cpp:34 - **FAILED** - Expecting: data == what.back() but 1 == 0 occured instead.
conditional.cpp:37 - **FAILED** - Expecting: data == what.front() but 1 == 0 occured instead.
conditional.cpp:40 - **FAILED** - Expecting: data == what.front() but 1 == 0 occured instead.
[SCENARIO] - Check store behavior with ignore (with T = eve::wide<float, eve::fixed<2>>)
Erreur de segmentation (core dumped)
```

Do not know what this is yet.

**Comment by DenisYaroshevskiy** [comment]
Ok for reduce tests I wrote a patch:
https://github.com/jfalcou/eve/pull/814

However, the store conditional mystifies me.

@jtlap 
Is this only floats?

This is the code that gets executed: 
https://github.com/jfalcou/eve/blob/4079d887f6d5b585bb88636a423d958752399249/include/eve/module/real/core/function/regular/simd/x86/store.hpp#L117-L126

We switched at some point from "we promise that the first elements of wide are 0" to "we don't guarantee what they are".
I suspect that there are garbage values before the beginning, when generating the mask

@jtlap - can I ask you to
bitcast this mask
https://github.com/jfalcou/eve/blob/4079d887f6d5b585bb88636a423d958752399249/include/eve/module/real/core/function/regular/simd/x86/store.hpp#L119

to `eve::logical<eve::wide<T>` and print that?

**Comment by jtlap** [comment]
here is the compilation and execution

avx2 clang12

cd /home/jt/falcoudev/build/clang-12/
ninja -k 0 unit.memory.store.conditional.exe
[1/5] Building CXX object CMakeFiles/test_pch.dir/cmake_pch.hxx.pch
[2/5] Building CXX object CMakeFiles/test_pch.dir/test/test_pch.cpp.o
[3/5] Linking CXX executable unit/test_pch
[4/5] Building CXX object 
test/unit/memory/CMakeFiles/unit.memory.store.conditional.exe.dir/store/conditional.cpp.o
[5/5] Linking CXX executable unit/unit.memory.store.conditional.exe

Compilation finished at Sat Jul 17 06:51:36

06:52:37 ~/falcoudev/build/clang-12$ unit/unit.memory.store.conditional.exe
[EVE] - Target: eve::avx2_ - Assertions: Disabled - PRNG Seed: 18102008
[SCENARIO] - Check store behavior with ignore (with T = eve::wide<float, 
eve::fixed<1ULL>>)
conditional.cpp:34 - **FAILED** - Expecting: data == what.back() but 
17.000000 == 1.000000 occured instead.
conditional.cpp:37 - **FAILED** - Expecting: data == what.front() but 
17.000000 == 1.000000 occured instead.
conditional.cpp:40 - **FAILED** - Expecting: data == what.front() but 
17.000000 == 1.000000 occured instead.
conditional.cpp:34 - **FAILED** - Expecting: data == what.back() but 1 
== 0 occured instead.
conditional.cpp:37 - **FAILED** - Expecting: data == what.front() but 1 
== 0 occured instead.
conditional.cpp:40 - **FAILED** - Expecting: data == what.front() but 1 
== 0 occured instead.
[SCENARIO] - Check store behavior with ignore (with T = eve::wide<float, 
eve::fixed<2>>)
Erreur de segmentation (core dumped)
06:52:42 ~/falcoudev/build/clang-12$

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

with g++11 I got a compile time error. Does it help ?


07:02:43 ~/falcoudev/build/g++-11$ ninja -k 0 
unit.memory.store.conditional.exe
[1/2] Building CXX object 
test/unit/memory/CMakeFiles/unit.memory.store.conditional.exe.dir/store/conditional.cpp.o
FAILED: 
test/unit/memory/CMakeFiles/unit.memory.store.conditional.exe.dir/store/conditional.cpp.o 

/usr/bin/g++-11  -I/home/jt/falcoudev/eve/test 
-I/home/jt/falcoudev/eve/include -mavx2 -O3 -DNDEBUG -std=c++20 -Werror 
-Wall -Wpedantic -Wextra -Winvalid-pch -include 
/home/jt/falcoudev/build/g++-11/CMakeFiles/test_pch.dir/cmake_pch.hxx 
-MD -MT 
test/unit/memory/CMakeFiles/unit.memory.store.conditional.exe.dir/store/conditional.cpp.o 
-MF 
test/unit/memory/CMakeFiles/unit.memory.store.conditional.exe.dir/store/conditional.cpp.o.d 
-o 
test/unit/memory/CMakeFiles/unit.memory.store.conditional.exe.dir/store/conditional.cpp.o 
-c /home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘double [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<double> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka ‘int 
[1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘long unsigned int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<long unsigned int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘unsigned int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<unsigned int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘long int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<long int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘float [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -1 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<float> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -7 is outside array bounds of ‘e_t [1]’ {aka ‘int 
[1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -7 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘long unsigned int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<long unsigned int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -7 is outside array bounds of ‘e_t [1]’ {aka 
‘unsigned int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -7 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<unsigned int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka ‘int 
[1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘long int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<long int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘double [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<double> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘float [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<float> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘unsigned int [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -3 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<unsigned int> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp: In lambda 
function:
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -7 is outside array bounds of ‘e_t [1]’ {aka 
‘float [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:33:74: 
error: array subscript -7 is outside array bounds of ‘e_t [1]’ {aka 
‘eve::logical<float> [1]’} [-Werror=array-bounds]
    33 |     eve::store[eve::ignore_first(T::size() - 1)](what, &data - 
T::size() + 1);
       | ~~~~~~~~~~~~~~~~~~^~~
/home/jt/falcoudev/eve/test/unit/memory/store/conditional.cpp:31:9: 
note: while referencing ‘data’
    31 |     e_t data;
       |         ^~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: cannot make progress due to previous errors.
07:04:39 ~/falcoudev/build/g++-11$


Le 17/07/2021 à 01:51, Denis Yaroshevskiy a écrit :

**Comment by jfalcou** [comment]
Isn't this fixed ?

**Comment by DenisYaroshevskiy** [comment]
Only one of them. The other needs conditional.mask fix

**Comment by jfalcou** [comment]
Reported as fixed
